### PR TITLE
fix: dont call deprecated method if using exactly version 8

### PR DESCRIPTION
**Pull request by mr-feek**
this should be a `<` instead of a `<=`

### CODE REVIEW

**Comment by thehappybug** [comment]
Hello @mr-feek. Thank you for your PR.

Will you be able to add/fix a unit test to cover this case?

**Comment by mr-feek** [comment]
My hunch is that https://github.com/apimatic/jsonmapper/blob/master/.github/workflows/test.yml#L27 installs the latest bugfix release on the 8.0 branch. Not sure how to specify to use _exactly_ 8.0 (Rather than, say, 8.0.8) as this bug is only reproducible in 8.0.0 🤔

**Comment by mr-feek** [comment]
yeah, doesn't seem possible https://github.com/shivammathur/setup-php/issues/456

**Review by thehappybug — APPROVED** [review]

**Comment by thehappybug** [comment]
@mr-feek Your fix is part of the release for https://github.com/apimatic/jsonmapper/releases/tag/v2.0.3.

**Pull request merged**
